## 데이터세트와 데이터로더: 다중 선형 회귀

In [1]:
import torch
from torch import nn
from torch import optim
from torch.utils.data import TensorDataset, DataLoader

train_x = torch.FloatTensor([
    [1, 2], [2, 3], [3, 4], [4, 5], [5, 6], [6, 7]
])
train_y = torch.FloatTensor([
    [0.1, 1.5], [1, 2.8], [1.9, 4.1], [2.8, 5.4], [3.7, 6.7], [4.6, 8]
])

In [2]:
train_dataset = TensorDataset(train_x, train_y)
train_dataloader = DataLoader(train_dataset, batch_size=2, shuffle=True, drop_last=True)

In [5]:
model = nn.Linear(2, 2, bias=False) # bias=True
criterion = nn.MSELoss()

lr = 0.001

optimizer = optim.SGD(model.parameters(), lr=lr)

In [6]:
epochs = 20000

for epoch in range(epochs):
    cost = 0.0

    for batch in train_dataloader:
        x, y = batch
        output = model(x)

        loss = criterion(output, y)

        optimizer.zero_grad()
        loss.backward()
        optimizer.step()

        cost += loss

    cost = cost / len(train_dataloader)

    if (epoch + 1) % 1000 == 0:
        print(f'Epoch : {epoch+1:4d}, Model : {list(model.parameters())}, Cost : {cost:.3f}')

Epoch : 1000, Model : [Parameter containing:
tensor([[0.4304, 0.2266],
        [0.6318, 0.5786]], requires_grad=True)], Cost : 0.116
Epoch : 2000, Model : [Parameter containing:
tensor([[0.6910, 0.0158],
        [0.7279, 0.5008]], requires_grad=True)], Cost : 0.073
Epoch : 3000, Model : [Parameter containing:
tensor([[ 0.8983, -0.1514],
        [ 0.8044,  0.4392]], requires_grad=True)], Cost : 0.047
Epoch : 4000, Model : [Parameter containing:
tensor([[ 1.0627, -0.2847],
        [ 0.8650,  0.3900]], requires_grad=True)], Cost : 0.030
Epoch : 5000, Model : [Parameter containing:
tensor([[ 1.1935, -0.3904],
        [ 0.9132,  0.3510]], requires_grad=True)], Cost : 0.018
Epoch : 6000, Model : [Parameter containing:
tensor([[ 1.2975, -0.4745],
        [ 0.9516,  0.3200]], requires_grad=True)], Cost : 0.012
Epoch : 7000, Model : [Parameter containing:
tensor([[ 1.3802, -0.5412],
        [ 0.9821,  0.2954]], requires_grad=True)], Cost : 0.007
Epoch : 8000, Model : [Parameter containing:
tens